### ISSUE TITLE
Import-Module : Could not load file... Newtonsoft.Json.dll

### ISSUE THREAD

**Issue by SpitFire-666** [camusicjunkie/PowerLFM#126]
I don't see the `lib `folder, let alone the `DLL `in the download or in the repo. Am I missing something? Running Win10, PS v5.1.

![image](https://user-images.githubusercontent.com/38451588/118396683-f615be80-b693-11eb-9e30-873fbdd0634a.png)

Thanks

**Comment by camusicjunkie** [comment]
Apologies for the very late response. How are you trying to install the module? That .dll isn't part of the repo. It's only added after a build and published to the gallery.

Try running `Install-Module PowerLFM` instead.
